version: '3.7'
services:
  db:
    image: "postgres"
    container_name: "postgres"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=testpass
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: "redis:alpine"
    container_name: "redis"
    command: redis-server
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  weatherservice:
    image: leaseplan-digital/weather-service:0.0.1-SNAPSHOT
    container_name: weather_service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DOCKER_GATEWAY_HOST:-host.docker.internal}:5432/postgres
      - SPRING_REDIS_HOST=${DOCKER_GATEWAY_HOST:-host.docker.internal}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    restart: on-failure