server:
  port: 8080

spring:
  application:
    name: weather-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: testpass
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    changeLog: classpath:db.changelog/db.changelog-master.yaml
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    timout: 60000

api:
  weather:
    appId: fbf9a0a1eaf3bf2b889225e311a2edd3
    appIdQueryParam: appid
    baseUrl: http://api.openweathermap.org/data/
    version: 2.5
    cacheTtlInHours: 24